server:
  port: ${PORT:8080}

spring:
  application:
    name: mini-postman
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    default-property-inclusion: non_null

app:
  history:
    storage-path: ${HISTORY_STORAGE_PATH:./data/history.json}
    max-items: ${HISTORY_MAX_ITEMS:500}

logging:
  level:
    com.mini_Postman: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
